### ISSUE TITLE
GCS: Gateway Error 504 on GET

### ISSUE THREAD

**Issue by klokan** [klokantech/cloudwrapper#15]
Sometimes Google Cloud Storage retrieval fails with 504 HTTP Gateway error on GET request.

We need to retry multiple times - with exponential backoff.

See: https://cloud.google.com/iot/docs/how-tos/exponential-backoff

@martinkostal can prepare a pull request - with the help/review of @MartinMikita - please.

Error example:

![Screenshot 2020-01-16 at 16 42 09](https://user-images.githubusercontent.com/26366957/72601482-c7f46300-3915-11ea-84e1-9816b99ba491.png)

**Comment by MartinMikita** [comment]
This is [included](https://github.com/klokantech/cloudwrapper/blob/master/cloudwrapper/gcs.py#L94..L109), but new types of Exceptions are risen, mostly caused by updates of the library itself.

To be improved.

**Comment by MartinMikita** [comment]
Fixed and released as version v2.1
