### ISSUE TITLE
Beanstalkd auto-reconnect

### ISSUE THREAD

**Issue by o1da** [klokantech/cloudwrapper#2]
@MartinMikita Is it possible to implement some auto-reconnect to Beanstalkd queue? I have a few Docker containers which use Beanstalkd container as queue, after the restart of Beanstalkd container  other containers return error on all queue interactions like:

```
Mon Jul  4 07:40:36 2016 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /tasks/vxxmitpfwd44/?callback=status_cb&random=0.8038788775086996 (ip 141.101.97.25) !!!
[pid: 15|app: 0|req: 50/50] 141.101.97.25 () {54 vars in 1040 bytes} [Mon Jul  4 07:40:36 2016] GET /tasks/vxxmitpfwd44/?callback=status_cb&random=0.8038788775086996 => generated 291 bytes in 3 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
```

And I have to restart other containers too.

**Comment by MartinMikita** [comment]
Done, update submodule/repository
