### ISSUE TITLE
Does License allow use in other projects?

### ISSUE THREAD

**Issue by lukasmartinelli** [klokantech/cloudwrapper#7]
Thanks for the improved work on cloudwrapper and Python module support.?

Not sure if I understand it but "Copyright Klokantech" does mean I do not have a right to use it in OSM2VectorTiles by default?

Perhaps you can choose a restrictive OSS license? (it could also restrict commercial use)

**Comment by klokan** [comment]
The license is now LGPL 2.1 - which permits use in a commercial as well as in an open-source project.
Modifications of the `cloudwrapper` library itself must be released as open-source again.
